version: "3.8"

services:
  ai-ide:
    build: .
    ports:
      - "3000:3000"
      - "11434:11434"
    volumes:
      - ./workspace:/app/workspace
    environment:
      - NODE_ENV=production
    restart: unless-stopped
